Repository bevyengine/bevy_editor_prototypes, pull requests merged in 2024-12, with the labels that each got.

#162 Update Roadmap
  design-book/src/roadmap.md
Labels: A-Meta

#160 Simplify context menu bugfix + option border radius adjustment
  bevy_widgets/bevy_context_menu/src/lib.rs
  bevy_widgets/bevy_context_menu/src/ui.rs
  crates/bevy_editor_styles/src/lib.rs
Labels: C-Code Quality, A-Widgets

#77 add functionally to load preferences/override from a toml file
  Cargo.toml
  crates/bevy_editor_settings/Bevy.toml
  crates/bevy_editor_settings/Cargo.toml
  crates/bevy_editor_settings/src/file_system/de/array.rs
  crates/bevy_editor_settings/src/file_system/de/default.rs
  crates/bevy_editor_settings/src/file_system/de/enums.rs
  crates/bevy_editor_settings/src/file_system/de/list.rs
  crates/bevy_editor_settings/src/file_system/de/map.rs
  crates/bevy_editor_settings/src/file_system/de/mod.rs
  crates/bevy_editor_settings/src/file_system/de/set.rs
  crates/bevy_editor_settings/src/file_system/de/struct_utils.rs
  crates/bevy_editor_settings/src/file_system/de/structs.rs
  crates/bevy_editor_settings/src/file_system/de/tuple.rs
  crates/bevy_editor_settings/src/file_system/de/tuple_struct.rs
  crates/bevy_editor_settings/src/file_system/de/tuple_utils.rs
  crates/bevy_editor_settings/src/file_system/de/value.rs
  crates/bevy_editor_settings/src/file_system/mod.rs
  crates/bevy_editor_settings/src/lib.rs
  crates/bevy_editor_settings/src/modals/editor.rs
  crates/bevy_editor_settings/src/modals/mod.rs
  crates/bevy_editor_settings/src/modals/project.rs
  crates/bevy_editor_settings/src/modals/user.rs
  crates/bevy_editor_settings/src/modals/workspace.rs
  crates/bevy_editor_settings/src/persistent.rs
Labels: C-Feature, A-Preferences
