Repository bevyengine/bevy_editor_prototypes, pull requests merged in 2024-11, with the labels that each got.

#153 , fix :)
  README.md
Labels: S-Ready-For-Final-Review

#154 Add `PaneDropArea` detection helper functions
  crates/bevy_pane_layout/src/lib.rs
  crates/bevy_pane_layout/src/pane_drop_area.rs
Labels: S-Ready-For-Final-Review

#158 Update to the latest `bevy` commit
  Cargo.toml
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  bevy_editor_panes/bevy_3d_viewport/src/lib.rs
  bevy_editor_panes/bevy_asset_browser/src/ui/nodes.rs
  bevy_widgets/bevy_menu_bar/src/lib.rs
  crates/bevy_editor_cam/src/extensions/anchor_indicator.rs
  crates/bevy_editor_cam/src/extensions/independent_skybox.rs
  crates/bevy_editor_launcher/src/ui.rs
  crates/bevy_infinite_grid/src/render/mod.rs
Labels: C-Dependencies

#159 Pane registry improvements
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  bevy_editor_panes/bevy_3d_viewport/src/lib.rs
  bevy_editor_panes/bevy_asset_browser/src/lib.rs
  bevy_editor_panes/bevy_asset_browser/src/ui/mod.rs
  crates/bevy_pane_layout/src/lib.rs
  crates/bevy_pane_layout/src/registry.rs
  crates/bevy_pane_layout/src/ui.rs
Labels: A-Panes, C-Code Quality
