Repository bevyengine/bevy_editor_prototypes, pull requests merged in 2024-10, with the labels that each got.

#53 Explain why the Bevy editor can't just be a plugin for existing tools
  design-book/src/design-constraints.md
Labels: S-Needs-Review, A-Meta

#56 Add more design guidelines
  design-book/src/best-practices.md
  design-book/src/design-paradigms.md
  design-book/src/general-patterns.md
Labels: A-Design

#79 Update to the latest `bevy` commit
  Cargo.toml
  bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/lib.rs
  crates/bevy_editor/src/ui.rs
  crates/bevy_editor_camera/examples/editor_camera_2d.rs
  projects/alien_cake_addict/src/main.rs
Labels: C-Dependencies

#80 Pane Layout System
  Cargo.toml
  bevy_editor_panes/bevy_3d_viewport/Cargo.toml
  bevy_editor_panes/bevy_3d_viewport/src/lib.rs
  crates/bevy_editor/Cargo.toml
  crates/bevy_editor/src/main.rs
  crates/bevy_editor_styles/src/lib.rs
  crates/bevy_pane_layout/Cargo.toml
  crates/bevy_pane_layout/src/handlers.rs
  crates/bevy_pane_layout/src/lib.rs
  crates/bevy_pane_layout/src/ui.rs
Labels: enhancement, A-Panes

#83 Limit pane resizing control to the primary mouse button
  crates/bevy_pane_layout/src/ui.rs
Labels: A-Panes

#84 Add 2D Viewport Pane
  bevy_editor_panes/bevy_2d_viewport/Cargo.toml
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  crates/bevy_editor/Cargo.toml
  crates/bevy_editor/src/main.rs
  crates/bevy_editor/src/ui.rs
  crates/bevy_editor_camera/src/editor_camera_2d/mod.rs
  crates/bevy_pane_layout/src/lib.rs
Labels: S-Needs-Review, A-Panes

#85 Vendor `bevy_infinite_grid`
  Cargo.toml
  crates/bevy_infinite_grid/Cargo.toml
  crates/bevy_infinite_grid/examples/simple.rs
  crates/bevy_infinite_grid/src/lib.rs
  crates/bevy_infinite_grid/src/render/grid.wgsl
  crates/bevy_infinite_grid/src/render/mod.rs
Labels: S-Needs-Review

#82 Cleanup unnecessary `allow` attributes
  bevy_editor_panes/bevy_marketplace_viewer/src/lib.rs
  crates/bevy_asset_preview/src/lib.rs
  crates/bevy_editor_camera/src/editor_camera_2d/mod.rs
  crates/bevy_editor_camera/src/lib.rs
  crates/bevy_pane_layout/src/lib.rs
  crates/bevy_undo/src/lib.rs
Labels: C-Code Quality

#86 Add 2D camera support to `bevy_infinite_grid`
  crates/bevy_infinite_grid/examples/simple_2d.rs
  crates/bevy_infinite_grid/src/render/mod.rs
Labels: C-Feature, S-Ready-For-Final-Review

#88 Update to the latest `bevy` commit
  Cargo.toml
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  bevy_widgets/bevy_menu_bar/src/lib.rs
  crates/bevy_editor/src/ui.rs
  crates/bevy_editor_camera/examples/editor_camera_2d.rs
  crates/bevy_editor_camera/src/editor_camera_2d/mod.rs
  crates/bevy_infinite_grid/examples/simple.rs
  crates/bevy_pane_layout/src/lib.rs
  crates/bevy_pane_layout/src/ui.rs
  crates/bevy_undo/examples/cube_move.rs
  projects/alien_cake_addict/src/main.rs
Labels: S-Needs-Review, C-Dependencies

#87 Add Context Menu Widget
  bevy_widgets/bevy_context_menu/Cargo.toml
  bevy_widgets/bevy_context_menu/examples/simple.rs
  bevy_widgets/bevy_context_menu/src/lib.rs
  bevy_widgets/bevy_context_menu/src/ui.rs
  crates/bevy_editor_styles/src/lib.rs
Labels: C-Feature, S-Needs-Review

#89 Move Pane Controls To A Context Menu
  bevy_widgets/bevy_context_menu/src/lib.rs
  crates/bevy_editor/Cargo.toml
  crates/bevy_editor/src/main.rs
  crates/bevy_pane_layout/Cargo.toml
  crates/bevy_pane_layout/src/handlers.rs
  crates/bevy_pane_layout/src/ui.rs
Labels: S-Needs-Review, A-Panes

#94 Update to the latest `bevy` commit
  Cargo.toml
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  bevy_widgets/bevy_context_menu/examples/simple.rs
  bevy_widgets/bevy_context_menu/src/lib.rs
  bevy_widgets/bevy_context_menu/src/ui.rs
  bevy_widgets/bevy_menu_bar/src/lib.rs
  crates/bevy_editor/src/ui.rs
  crates/bevy_pane_layout/src/lib.rs
  crates/bevy_pane_layout/src/ui.rs
  projects/alien_cake_addict/src/main.rs
Labels: C-Dependencies

#97 Fix context menu not appearing + Add drop shadow
  bevy_widgets/bevy_context_menu/src/lib.rs
  bevy_widgets/bevy_context_menu/src/ui.rs
Labels: C-Bug

#95 Add bevy wayland feature
  Cargo.toml
Labels: C-Bug, X-Contentious, A-Crosscutting

#103 Viewport node + Pane header fixes
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  crates/bevy_pane_layout/src/ui.rs
Labels: C-Bug

#92 Fix Pane Jitter
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
Labels: C-Bug, A-Panes

#105 Vendor `bevy_editor_cam`
  Cargo.toml
  crates/bevy_editor_cam/Cargo.toml
  crates/bevy_editor_cam/examples/cad.rs
  crates/bevy_editor_cam/examples/map.rs
  crates/bevy_editor_cam/examples/minimal.rs
  crates/bevy_editor_cam/examples/ortho.rs
  crates/bevy_editor_cam/examples/pseudo_ortho.rs
  crates/bevy_editor_cam/examples/split_screen.rs
  crates/bevy_editor_cam/examples/zoom_limits.rs
  crates/bevy_editor_cam/src/controller/component.rs
  crates/bevy_editor_cam/src/controller/inputs.rs
  crates/bevy_editor_cam/src/controller/mod.rs
  crates/bevy_editor_cam/src/controller/momentum.rs
  crates/bevy_editor_cam/src/controller/motion.rs
  crates/bevy_editor_cam/src/controller/projections.rs
  crates/bevy_editor_cam/src/controller/smoothing.rs
  crates/bevy_editor_cam/src/controller/zoom.rs
  crates/bevy_editor_cam/src/extensions/anchor_indicator.rs
  crates/bevy_editor_cam/src/extensions/dolly_zoom.rs
  crates/bevy_editor_cam/src/extensions/independent_skybox.rs
  crates/bevy_editor_cam/src/extensions/look_to.rs
  crates/bevy_editor_cam/src/extensions/mod.rs
  crates/bevy_editor_cam/src/input.rs
  crates/bevy_editor_cam/src/lib.rs
Labels: S-Needs-Review, C-Dependencies, A-Camera

#78 Asset browser V1
  Cargo.toml
  bevy_editor_panes/bevy_asset_browser/Cargo.toml
  bevy_editor_panes/bevy_asset_browser/src/assets/directory_icon.png
  bevy_editor_panes/bevy_asset_browser/src/assets/directory_icon.svg
  bevy_editor_panes/bevy_asset_browser/src/assets/file_icon.png
  bevy_editor_panes/bevy_asset_browser/src/assets/file_icon.svg
  bevy_editor_panes/bevy_asset_browser/src/assets/source_icon.png
  bevy_editor_panes/bevy_asset_browser/src/assets/source_icon.svg
  bevy_editor_panes/bevy_asset_browser/src/directory_content.rs
  bevy_editor_panes/bevy_asset_browser/src/lib.rs
  bevy_editor_panes/bevy_asset_browser/src/top_bar.rs
  crates/bevy_editor/Cargo.toml
  crates/bevy_editor/src/main.rs
  crates/bevy_pane_layout/src/lib.rs
Labels: C-Feature, S-Needs-Review, A-Assets

#106 Fix `AssetBrowserLocation` crash
  bevy_editor_panes/bevy_asset_browser/src/directory_content.rs
Labels: C-Bug, A-Assets

#112 Add `rfd` dependency
  Cargo.toml
Labels: C-Dependencies

#115 Enable workspace lints in `bevy_editor_cam`
  crates/bevy_editor_cam/Cargo.toml
  crates/bevy_editor_cam/examples/cad.rs
  crates/bevy_editor_cam/examples/map.rs
  crates/bevy_editor_cam/examples/ortho.rs
  crates/bevy_editor_cam/src/controller/component.rs
  crates/bevy_editor_cam/src/controller/inputs.rs
  crates/bevy_editor_cam/src/controller/mod.rs
  crates/bevy_editor_cam/src/controller/motion.rs
  crates/bevy_editor_cam/src/controller/smoothing.rs
  crates/bevy_editor_cam/src/extensions/anchor_indicator.rs
  crates/bevy_editor_cam/src/extensions/dolly_zoom.rs
  crates/bevy_editor_cam/src/extensions/independent_skybox.rs
  crates/bevy_editor_cam/src/extensions/look_to.rs
  crates/bevy_editor_cam/src/input.rs
Labels: C-Code Quality

#114 Fix Camera Anchor Indicator
  crates/bevy_editor_cam/src/extensions/anchor_indicator.rs
  crates/bevy_editor_cam/src/extensions/assets/license.md
  crates/bevy_editor_cam/src/extensions/assets/tilt-shift.png
  crates/bevy_editor_cam/src/lib.rs
Labels: C-Bug, A-Camera

#125 Switch to the Inter UI font.
  LICENSE-SIL-OFL
  bevy_editor_panes/bevy_asset_browser/src/directory_content.rs
  bevy_editor_panes/bevy_asset_browser/src/top_bar.rs
  bevy_widgets/bevy_context_menu/src/ui.rs
  bevy_widgets/bevy_footer_bar/src/lib.rs
  bevy_widgets/bevy_menu_bar/src/lib.rs
  crates/bevy_editor_styles/src/assets/fonts/Inter-Regular.ttf
  crates/bevy_editor_styles/src/lib.rs
  crates/bevy_pane_layout/src/ui.rs
Labels: S-Needs-Review, A-Design, C-Usability

#124 Add menu item for loading GLTF files
  crates/bevy_editor/Cargo.toml
  crates/bevy_editor/src/load_gltf.rs
  crates/bevy_editor/src/main.rs
Labels: C-Feature

#132 Infinite scaling grid
  bevy_editor_panes/bevy_2d_viewport/src/lib.rs
  crates/bevy_infinite_grid/examples/simple_2d.rs
  crates/bevy_infinite_grid/src/render/grid.wgsl
Labels: C-Feature

#138 Add basic glossary
  design-book/src/SUMMARY.md
  design-book/src/glossary.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Crosscutting

#135 Launcher and Projects
  Cargo.toml
  crates/bevy_editor/Cargo.toml
  crates/bevy_editor/src/lib.rs
  crates/bevy_editor/src/project/cache.rs
  crates/bevy_editor/src/project/mod.rs
  crates/bevy_editor/src/project/templates.rs
  crates/bevy_editor_launcher/Cargo.toml
  crates/bevy_editor_launcher/assets/image-off.png
  crates/bevy_editor_launcher/assets/image-off.svg
  crates/bevy_editor_launcher/assets/plus.png
  crates/bevy_editor_launcher/assets/plus.svg
  crates/bevy_editor_launcher/src/main.rs
  crates/bevy_editor_launcher/src/ui.rs
  projects/alien_cake_addict/Cargo.toml
  templates/blank_project/Cargo.toml
  templates/blank_project/src/main.rs
  templates/getting_started/Cargo.toml
  templates/getting_started/assets/models/alien.glb
  templates/getting_started/assets/models/cakeBirthday.glb
  templates/getting_started/assets/models/tile.glb
  templates/getting_started/src/main.rs
Labels: A-Launcher
